### ISSUE TITLE
div II feedback

### ISSUE THREAD

**Issue by mariumtapal** [ajhaller/IPEDS#1]
looking at last commit [2bdc53d](https://github.com/ajhaller/-IPEDS/commit/2bdc53d0ae4fcc2fb1edaef88d29e63728b90ddb)

1. Passes `install_github`: ✅
2. Documentation builds: ✅
3. Passes R CMD check: ✅

@beanumber

**Comment by beanumber** [comment]
I can't clone this repo because of the `-` in the repository name!! Please, please, please remove the `-` from the repository name.

**Comment by ajhaller** [comment]
Sorry! I think I fixed it. Let me know if it doesn't work!

**Comment by ajhaller** [comment]
div 2 checked
